name: Terraform CI

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  pull-requests: write   # so we can post the plan in the job summary
  id-token: write        # future-proof if we switch to OIDC (no secrets)

jobs:
  terraform:
    name: fmt + validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (no backend auth needed for validate)
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

  plan:
    name: terraform plan
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Configure AWS creds from Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # If you pass region via variable, this keeps TF in sync with the secret.
      - name: Terraform Init
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: terraform init -input=false

      - name: Terraform Plan (save to file)
        env:
          TF_VAR_aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform plan -no-color -input=false -out tfplan.binary
          terraform show -no-color tfplan.binary > tfplan.txt

      # Show the plan directly in the PR/job summary (first ~300 lines to keep it readable)
      - name: Add plan to job summary
        run: |
          echo "### Terraform Plan" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          sed -n '1,300p' tfplan.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_Full plan saved as artifact below._" >> $GITHUB_STEP_SUMMARY

      - name: Upload full plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan.txt
          path: tfplan.txt
