# Trigger workflow again
name: Terraform Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate -no-color
<<<<<<< HEAD
plan:   
    runs-on: ubuntu-latest
    needs: terraform   # waits until 'terraform' job passes first
=======
  plan:
    runs-on: ubuntu-latest
    needs: terraform
>>>>>>> b79916f46347e17d29ac8ca091dc749c342b2877

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (no backend)
        run: terraform init -backend=false

      - name: Terraform Plan
        run: terraform plan -no-color
<<<<<<< HEAD

=======
>>>>>>> b79916f46347e17d29ac8ca091dc749c342b2877
